routes/web.php
<?php

use App\Http\Controllers\GroupCourseWithTeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentGroupController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('courses', CourseController::class)->except('show');
Route::resource('teachers', TeacherController::class)->except('show');
Route::resource('student-groups', StudentGroupController::class)->except('show');
Route::resource('students', StudentController::class)->except('show');

Route::resource('group-course-with-teachers', GroupCourseWithTeacherController::class)->except('show')->except('create')->except('edit');
Route::post('group-course-with-teachers/getCourses', [GroupCourseWithTeacherController::class, 'getCoursesAjax'])->name('getCoursesAjax');
Route::get('group-course-with-teachers/create/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'create'])->name('group-course-with-teachers.create');
Route::get('group-course-with-teachers/edit/{groupCourseWithTeacher}/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'edit'])->name('group-course-with-teachers.edit');

resources/views/index.blade.php
@extends('layouts.main')

resources/views/menu.blade.php
<li class="nav-item"><a class="nav-link" href="{{ route('courses.index') }}">Курсы</a></li>
<li class="nav-item"><a class="nav-link" href="{{ route('teachers.index') }}">Преподаватели</a></li>
<li class="nav-item"><a class="nav-link" href="{{ route('student-groups.index') }}">Группы</a></li>
<li class="nav-item"><a class="nav-link" href="{{ route('students.index') }}">Студенты</a></li>
<li class="nav-item dropdown">
    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <b> Добавить </b>
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ route('courses.create') }}">Курс</a>
        <a class="dropdown-item" href="{{ route('teachers.create') }}">Преподавателя</a>
        <a class="dropdown-item" href="{{ route('student-groups.create') }}">Группу</a>
        <a class="dropdown-item" href="{{ route('students.create') }}">Студента</a>
    </div>
</li>
<li class="nav-item"><a class="nav-link" href="{{ route('group-course-with-teachers.index') }}">Назначение преподавателя</a></li>