routes/web.php
<?php

use App\Http\Controllers\GroupCourseWithTeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentGroupController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('courses', CourseController::class)->except('show');
Route::resource('teachers', TeacherController::class)->except('show');
Route::resource('student-groups', StudentGroupController::class)->except('show');
Route::resource('students', StudentController::class)->except('show');

Route::resource('group-course-with-teachers', GroupCourseWithTeacherController::class)->except('show')->except('create')->except('edit');
Route::post('group-course-with-teachers/getCourses', [GroupCourseWithTeacherController::class, 'getCoursesAjax'])->name('getCoursesAjax');
Route::get('group-course-with-teachers/create/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'create'])->name('group-course-with-teachers.create');
Route::get('group-course-with-teachers/edit/{groupCourseWithTeacher}/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'edit'])->name('group-course-with-teachers.edit');

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
        'name'
    ];

    use HasFactory;

    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TeacherRequest;
use App\Models\Course;
use App\Models\StudentGroup;
use App\Models\Teacher;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        return view('teachers.index', [
            'teachers' => Teacher::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(Teacher $teacher)
    {
        return view('teachers.create', [
            'teacher' => $teacher,
            'courses' => Course::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     */
    public function store(TeacherRequest $request, Teacher $teacher)
    {
        $request->validated();
        //Create new Teacher
        $teacher->fill($request->except(['courses']))->save();
        //Courses attach
        if ($request->has('courses')) {
            $teacher->courses()->attach($request->input('courses'));
        }

        return redirect()->route('teachers.edit', $teacher)->with('notification', 'Преподаватель создан');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Teacher $teacher
     */
    public function edit(Teacher $teacher)
    {
        return view('teachers.create', [
            'teacher' => $teacher,
            'courses' => Course::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Models\Teacher $teacher
     */
    public function update(TeacherRequest $request, Teacher $teacher)
    {
        $request->validated();
        //Update current Teacher
        $teacher->fill($request->except(['courses']))->save();
        //Courses detach
        $teacher->courses()->detach();
        //Courses attach
        if ($request->has('courses')) {
            $teacher->courses()->attach($request->input('courses'));
        }

        return redirect()->route('teachers.edit', $teacher)->with('notification', 'Преподаватель изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Teacher $teacher
     */
    public function destroy(Teacher $teacher)
    {
        try {
            $teacher->delete();
        } catch (QueryException $e) {
            if ($e->errorInfo[1] == 1451) {
                return redirect()->route('teachers.index')
                    ->with('alert', "Нельзя удалить преподавателя, так как к нему привязаны курсы");
            }
        }
        return redirect()->route('teachers.index')
            ->with('notification', 'Преподаватель удален');
    }
}

resources/views/teachers/create.blade.php
@extends('layouts.main')
@section('title', 'Преподаватель')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card p-3">
                    <h1 class="text-center mb-3">@if(!$teacher->id)Создание преподавателя@elseИзменение преподавателя@endif</h1>

                    <div class="card-body">
                        <form method="post"
                              action="@if(!$teacher->id) {{ route('teachers.store') }} @else {{ route('teachers.update', $teacher) }} @endif"
                              enctype="multipart/form-data">
                            @csrf
                            @if($teacher->id) @method('PUT')@endif

                            <div class="form-group">
                                <label for="newsTitle"><h3>Имя преподавателя</h3></label>
                                @error('name')
                                <div class="alert alert-danger col-md-6">{{ $message }}</div>
                                @enderror
                                <input class="form-control col-md-6" id="newsTitle" type="text" name="name"
                                       value="{{ old('name') ?? $teacher->name }}">
                            </div>
                            <hr>
                            <h3>Какие курсы может преподавать</h3>
                            @error('courses')
                            <div class="alert alert-danger col-md-6">{{ $message }}</div>
                            @enderror
                            <div class="form-check d-flex flex-wrap">
                                @forelse($courses as $course)
                                    <div class="mr-5">
                                        <input class="form-check-input" type="checkbox" name="courses[]" multiple
                                               value="{{ $course->id }}"
                                               id="{{$course->id . '-' . $course->name}}"
                                               @if($teacher->courses->contains('id', $course->id)) checked="" @endif>
                                        <label
                                            for="{{$course->id . '-' . $course->name}}">{{ $course->name }}</label><br>
                                    </div>
                                @empty
                                @endforelse
                            </div>
                            <hr>
                            <div class="form-group">
                                <input class="btn btn-outline-primary" type="submit"
                                       value="@if($teacher->id)Изменить@elseСоздать@endif преподавателя">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/teachers/index.blade.php
@extends('layouts.main')

@section('title', 'Преподаватели')
@section('content')
    <div class="container">
        <div class="justify-content-center">
            <div class="card pt-3">
                <h1 class="text-center mb-3">Преподаватели</h1>

                <table class="table table-striped text-center">
                    <tr>
                        <td><b>№</b></td>
                        <td><b>Имя преподавателя</b></td>
                        <td><b>Какие курсы может вести</b></td>
                        <td><b>Действия</b></td>
                    </tr>
                    @php ($i = 1)
                    @forelse($teachers as $teacher)
                        <tr>
                            <td style="vertical-align: middle"> {{ $i++ }} </td>
                            <td style="vertical-align: middle">{{ $teacher->name }}</td>
                            <td style="vertical-align: middle">
                                @forelse($teacher->courses as $course)
                                    {{ $course->name  }} <br>
                                @empty
                                    <span style="color: #b91d19">Курсы не определены</span>
                                @endif
                            </td>
                            <td style="vertical-align: middle">
                                <ul class="nav justify-content-center">
                                    <li class="mr-3">
                                        <a href="{{ route('teachers.edit', $teacher) }}" class="btn btn-primary">
                                            <i class="bi bi-pencil-square" style="font-size: 1rem"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <form method="post" action="{{ route('teachers.destroy', $teacher) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">
                                                <i class="bi bi-trash" style="font-size: 1rem"></i>
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @empty

                    @endforelse
                </table>
            </div>
        </div>
    </div>
@endsection