routes/web.php
<?php

use App\Http\Controllers\GroupCourseWithTeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentGroupController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('courses', CourseController::class)->except('show');
Route::resource('teachers', TeacherController::class)->except('show');
Route::resource('student-groups', StudentGroupController::class)->except('show');
Route::resource('students', StudentController::class)->except('show');

Route::resource('group-course-with-teachers', GroupCourseWithTeacherController::class)->except('show')->except('create')->except('edit');
Route::post('group-course-with-teachers/getCourses', [GroupCourseWithTeacherController::class, 'getCoursesAjax'])->name('getCoursesAjax');
Route::get('group-course-with-teachers/create/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'create'])->name('group-course-with-teachers.create');
Route::get('group-course-with-teachers/edit/{groupCourseWithTeacher}/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'edit'])->name('group-course-with-teachers.edit');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name',
        'student_group_id',
        'photo'
    ];

    use HasFactory;

    public function studentGroup()
    {
        return $this->belongsTo(StudentGroup::class, 'student_group_id');
    }

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Models\Course;
use App\Models\Student;
use App\Models\StudentGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $students = Student::paginate(20);
        return view('students.index', [
            'students' => $students
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(Student $student)
    {
        return view('students.create', [
            'student' => $student,
            'studentGroups' => StudentGroup::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     */
    public function store(StudentRequest $request, Student $student)
    {
        $request->validated();
        //Photo handler
        if ($request->file('photo')) {
            $path = Storage::putFileAs('public/images/students', $request->file('photo'), $request->file('photo')->getClientOriginalName());
            $url = Storage::url($path);

            $student->photo = $url;
        }
        //Create new Student
        $student->fill($request->except('photo'))->save();

        return redirect()->route('students.edit', $student)->with('notification', 'Студент создан');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Student $student
     */
    public function edit(Student $student)
    {
        return view('students.create', [
            'student' => $student,
            'studentGroups' => StudentGroup::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Models\Student $student
     */
    public function update(StudentRequest $request, Student $student)
    {
        $request->validated();
        //Photo handler
        if ($request->file('photo')) {
            $path = Storage::putFileAs('public/images/students', $request->file('photo'), $request->file('photo')->getClientOriginalName());
            $url = Storage::url($path);

            $student->photo = $url;
        }
        //Update current Student
        $student->fill($request->except('photo'))->save();

        return redirect()->route('students.edit', $student)->with('notification', 'Студент изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Student $student
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index', $student)->with('notification', 'Студент удален');
    }
}

resources/views/students/create.blade.php
@extends('layouts.main')
@section('title', 'Преподаватель')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card p-3">
                    <h1 class="text-center mb-3">@if(!$student->id)Создание студента@elseИзменение
                        студента@endif</h1>

                    <div class="card-body">
                        <form method="post"
                              action="@if(!$student->id) {{ route('students.store') }} @else {{ route('students.update', $student) }} @endif"
                              enctype="multipart/form-data">
                            @csrf
                            @if($student->id) @method('PUT')@endif

                            <div class="form-group">
                                <label for="newsTitle"><h3>Имя студента</h3></label>
                                @error('name')
                                <div class="alert alert-danger col-md-6">{{ $message }}</div>
                                @enderror
                                <input class="form-control col-md-6" id="newsTitle" type="text" name="name"
                                       value="{{ old('name') ?? $student->name }}">
                            </div>
                            <hr>
                            <h3>В какой группе</h3>
                            @error('groups')
                            <div class="alert alert-danger col-md-6">{{ $message }}</div>
                            @enderror
                            <div class="form-group">
                                <select class="form-control col-md-3" name="student_group_id">
                                    @foreach($studentGroups as $group)
                                        <option
                                            @if($group->id == $student->student_group_id)
                                            selected
                                            @endif
                                            value="{{ $group->id }}">{{ $group->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <hr>
                            <h3>Фото студента</h3>
                            <div class="student-photo mb-3">
                                @error('photo')
                                <div class="alert alert-danger col-md-6">{{ $message }}</div>
                                @enderror
                                <div class="custom-file col-6 mb-2">
                                    <input onchange="setFilename()" id="newsImage" name="photo" type="file"
                                           class="custom-file-input">
                                    <label
                                        class="custom-file-label">@if($student->photo){{ last(explode('/', $student->photo)) }} @else
                                            Выберите файл@endif</label>
                                </div>
                                <p>Желательно загружать изображение размером 120х120px</p>
                            @if($student->photo)
                                    <div class="news-img-item">
                                        <img width="120px" src="{{ asset($student->photo) }}"
                                             alt="{{ $student->name }}">
                                    </div>
                                @endif
                            </div>
                            <hr>
                            <div class="form-group">
                                <input class="btn btn-outline-primary" type="submit"
                                       value="@if($student->id)Изменить@elseСоздать@endif студента">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

<script type="text/javascript">
    function setFilename() {
        var fileName = document.getElementById("newsImage").files[0].name;
        var label = document.getElementsByClassName('custom-file-label');
        label[0].innerHTML = fileName;
    }
</script>

resources/views/students/index.blade.php
@extends('layouts.main')

@section('title', 'Студенты')
@section('content')
    <div class="container">
        <div class="justify-content-center">
            <div class="card pt-3">
                <h1 class="text-center mb-3">Студенты</h1>

                <table class="table table-striped text-center">
                    <tr>
                        <td><b>ID</b></td>
                        <td><b>Имя стужента</b></td>
                        <td><b>В какой группе</b></td>
                        <td><b>Действия</b></td>
                    </tr>

                    @forelse($students as $student)
                        <tr>
                            <td style="vertical-align: middle"> {{ $student->id }} </td>
                            <td style="vertical-align: middle">{{ $student->name }}</td>
                            <td style="vertical-align: middle">{{$student->studentGroup->name}}</td>
                            <td style="vertical-align: middle">
                                <ul class="nav justify-content-center">
                                    <li class="mr-3">
                                        <a href="{{ route('students.edit', $student) }}" class="btn btn-primary">
                                            <i class="bi bi-pencil-square" style="font-size: 1rem"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <form method="post" action="{{ route('students.destroy', $student) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">
                                                <i class="bi bi-trash" style="font-size: 1rem"></i>
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @empty
                    @endforelse
                </table>
                {{ $students->links() }}
            </div>
        </div>
    </div>
@endsection