routes/web.php
<?php

use App\Http\Controllers\GroupCourseWithTeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentGroupController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('courses', CourseController::class)->except('show');
Route::resource('teachers', TeacherController::class)->except('show');
Route::resource('student-groups', StudentGroupController::class)->except('show');
Route::resource('students', StudentController::class)->except('show');

Route::resource('group-course-with-teachers', GroupCourseWithTeacherController::class)->except('show')->except('create')->except('edit');
Route::post('group-course-with-teachers/getCourses', [GroupCourseWithTeacherController::class, 'getCoursesAjax'])->name('getCoursesAjax');
Route::get('group-course-with-teachers/create/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'create'])->name('group-course-with-teachers.create');
Route::get('group-course-with-teachers/edit/{groupCourseWithTeacher}/{studentGroup}/{course}', [GroupCourseWithTeacherController::class, 'edit'])->name('group-course-with-teachers.edit');

resources/views/courses/create.blade.php
@extends('layouts.main')
@section('title', 'Курс')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card p-3">
                    <h1 class="text-center mb-3">@if(!$course->id)Создание курса@elseИзменение курса@endif</h1>

                    <div class="card-body">
                        <form method="post"
                              action="@if(!$course->id) {{ route('courses.store') }} @else {{ route('courses.update', $course) }} @endif"
                              enctype="multipart/form-data">
                            @csrf
                            @if($course->id) @method('PUT')@endif

                            <div class="form-group">
                                <label for="newsTitle"><h3>Наименование курса</h3></label>
                                @error('name')
                                <div class="alert alert-danger col-md-6">{{ $message }}</div>
                                @enderror
                                <input class="form-control col-md-6" id="newsTitle" type="text" name="name"
                                       value="{{ old('name') ?? $course->name }}">
                            </div>
                            <hr>
                            <h3>Кто может преподавать</h3>
                            @error('teachers')
                            <div class="alert alert-danger col-md-6">{{ $message }}</div>
                            @enderror
                            <div class="form-check d-flex flex-wrap">
                                @forelse($teachers as $teacher)
                                    <div class="mr-5">
                                        <input class="form-check-input" type="checkbox" name="teachers[]" multiple
                                               value="{{ $teacher->id }}"
                                               id="{{$teacher->id . '-' . $teacher->name}}"
                                               @if($course->teachers->contains('id', $teacher->id)) checked="" @endif>
                                        <label
                                            for="{{$teacher->id . '-' . $teacher->name}}">{{ $teacher->name }}</label><br>
                                    </div>
                                @empty
                                @endforelse
                            </div>
                            <hr>
                            <h3>В каких групах должен преподаваться</h3>
                            @error('studentGroups')
                            <div class="alert alert-danger col-md-6">{{ $message }}</div>
                            @enderror
                            <div class="form-check d-flex flex-wrap">
                                @foreach($studentGroups as $studentGroup)
                                    <div class="mr-5">
                                        <input class="form-check-input" type="checkbox" name="studentGroups[]" multiple
                                               value="{{ $studentGroup->id }}"
                                               id="{{$studentGroup->id . '-' . $studentGroup->name}}"
                                               @if($course->studentGroups->contains('id', $studentGroup->id)) checked="" @endif>
                                        <label
                                            for="{{$studentGroup->id . '-' . $studentGroup->name}}">{{ $studentGroup->name }}</label><br>
                                    </div>
                                @endforeach
                            </div>
                            <hr>
                            <div class="form-group">
                                <input class="btn btn-outline-primary" type="submit"
                                       value="@if($course->id)Изменить@elseСоздать@endif курс">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/courses/index.blade.php
@extends('layouts.main')

@section('title', 'Курсы')
@section('content')
    <div class="container">
        <div class="justify-content-center">
            <div class="card pt-3">
                <h1 class="text-center mb-3">Курсы</h1>

                <table class="table table-striped text-center">
                    <tr>
                        <td><b>№</b></td>
                        <td><b>Название курса</b></td>
                        <td><b>Могут преподавать</b></td>
                        <td><b>В каких группах должен проходить</b></td>
                        <td><b>Дата создания</b></td>
                        <td><b>Действия</b></td>
                    </tr>
                    @php ($i = 1)
                    @forelse($courses as $course)
                        <tr>
                            <td style="vertical-align: middle"> {{ $i++ }} </td>
                            <td style="vertical-align: middle">{{ $course->name }}</td>
                            <td style="vertical-align: middle">
                                @forelse($course->teachers as $teacher)
                                    {{ $teacher->name  }} <br>
                                @empty
                                    <span style="color: #b91d19">Преподаватели не назначены</span>
                                @endif
                            </td>
                            <td style="vertical-align: middle">
                                @forelse($course->studentGroups as $group)
                                    {{ $group->name }} <br>
                                @empty
                                    <span style="color: #b91d19"> Не назначен ни одной группе </span>
                                @endif
                            </td>
                            <td style="vertical-align: middle">{{ $course->created_at ?? '00-00-000'}}</td>
                            <td style="vertical-align: middle">
                                <ul class="nav justify-content-center">
                                    <li class="mr-3">
                                        <a href="{{ route('courses.edit', $course) }}" class="btn btn-primary">
                                            <i class="bi bi-pencil-square" style="font-size: 1rem"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <form method="post" action="{{ route('courses.destroy', $course) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">
                                                <i class="bi bi-trash" style="font-size: 1rem"></i>
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @empty

                    @endforelse
                </table>
            </div>
        </div>
    </div>
@endsection